spring.application.name=digital-banking
server.port=8085

spring.datasource.url=jdbc:h2:mem:banque-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# MySQL (décommenter pour la prod)
# spring.datasource.url=jdbc:mysql://localhost:3306/banque?createDatabaseIfNotExist=true
# spring.datasource.username=root
# spring.datasource.password=
# spring.jpa.hibernate.ddl-auto=update
